### ISSUE TITLE
Infografía Matemáticas Discretas: Actividad 1 Infografía Sistema de numeración 

### ISSUE THREAD

**Issue by LenninGS-0** [SistemasTecTlaxiaco/infografia-LenninGS-0#1]
[INFOGRAFIA DE LOS SISTEMAS NUMERICOS.pdf](https://github.com/user-attachments/files/16734927/INFOGRAFIA.DE.LOS.SISTEMAS.NUMERICOS.pdf)

**Comment by AlynGomez12** [comment]
Redacción y Ortografía:13/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:14/14
Referencias:14/14
Presentación:14/14
Calificación Final: 19.8/20
Agregar nombre del alumno y grupo.

**Comment by AlynGomez12** [comment]
Agregar nombre del alumno y grupo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
